[package]
name = "lude"
version = "0.1.0"
authors = ["user"]
edition = "2018"

[dependencies]
debug_stub_derive = "0.3.0"
indexmap = "1.3.0"
clap = "2.33.0"
pest = "2.1.2"
pest_derive = "2.1.0"
jack = "0.6.2"
ears = "0.7.0"
sndfile-sys = "0.2.0"
lazy_static = "1.4.0"
