[package]
name = "jam-seqs"
version = "0.1.0"
authors = ["user"]
edition = "2018"

[dependencies]
debug_stub_derive = "0.3.0"
clap = "2.33.0"
ears = "0.7.0"
indexmap = "1.3.0"
pest = "2.1.2"
pest_derive = "2.1.0"
