#!/usr/bin/env bash

set -aeu
pushd `dirname $0`;trap "popd>/dev/null" EXIT

getSourceFiles () {
  find ./src \( -iname "*" ! -iname ".*" \)
}

ToRunTests="cargo test -- --nocapture --test-threads=1"

runTests () {
  $ToRunTests
}

loopTests () {
  getSourceFiles | entr -c "$ToRunTests"
}

ToRenderExample="cargo run example/test_02.seq"

loopRender () {
  getSourceFiles | entr -c "$ToRenderExample"
}

pushd $(dirname $(realpath $0)) > /dev/null
$@
popd > /dev/null
