#!/usr/bin/env bash

set -ae

build () {
 cargo build
}

tests () {
 ./target/debug/jam-seqs ./examples/03_minimal.seq
}

iterate () {
 #!/bin/sh
 ./dev build && ./dev test
}

build-nix () {
 time nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}' $@
}

test-nix () {
 ./result/bin/jam-seqs ./examples/03_minimal.seq
}

iterate () {
 ./dev build && ./dev tests
}

pushd $(dirname $(realpath $0)) > /dev/null
$@
popd > /dev/null
